PRINT_STATEMENTS_HASH = { "welcome" => "\n\n Welcome Admin" ,
                          "size_limit" => Proc.new {|variable| "\n\n Parking lot size limit reached: #{variable}"},
                          "enter_license" => "\n\n Enter License Plate Number: ",
                          "enter_invoice" => "\n\n Enter Invoice_ID: ",
                          "valid_plate" => "\n\n Enter a valid license plate",
                          "license_exists" => "\n\n License Plate exists in the record",
                          "car_added" => Proc.new {|car_no| "\n\n #{car_no} - Car added to the entry"},
                          "license_not_found" => "\n\n license plate not found",
                          "no_cars_present" => "\n\n No cars present in parking lot",
                          "invoice_not_found" => "\n\n Invoice ID not found",
                          "select_format" => "\n\n Select the format of the file",
                          "no_invoices_found" => "\n\n No invoices found",
                          "parking_name" => "\n\n Enter the parking lot name: ",
                          "parking_exists" => "\n\n Parking lot already exists.",
                          "lot_created" => Proc.new {|lot_name| "\n\n #{lot_name} - Parking lot created successfully"},
                          "lot_name" => "\n\n Enter the parking lot name:",
                          "lot_not_found" => "\n\n Parking lot not found.",
                          "invalid_lot" => "\n\n nInvalid parking lot name.",
                          "invalid_lot" => "\n\n nInvalid parking lot name.",
                          "lot_removed" => Proc.new {|lot_name| "\n\n #{lot_name} - Parking Lot removed successfully."},
                          "lots_not_found" => "\n\n No Parking lots found.",
                        }

# puts PRINT_STATEMENTS_HASH["size_limit"].call(10)